name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [ frontend, backend ]

    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm ci

      - name: Rodar testes
        run: npm test
